services:
  - type: web
    name: barangay-daang-bakal-web
    env: docker
    repo: https://github.com/meshamay/barangay_daang_bakal_system
    branch: master
    plan: starter
    dockerfilePath: Dockerfile
    autoDeploy: true
    pullRequestPreviews: false
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: 'false'
      - key: APP_URL
        fromSecret: APP_URL
      - key: APP_KEY
        fromSecret: APP_KEY
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        fromSecret: DB_HOST
      - key: DB_PORT
        fromSecret: DB_PORT
      - key: DB_DATABASE
        fromSecret: DB_DATABASE
      - key: DB_USERNAME
        fromSecret: DB_USERNAME
      - key: DB_PASSWORD
        fromSecret: DB_PASSWORD
      - key: QUEUE_CONNECTION
        value: sync
